# Generated by Django 2.1a1 on 2018-06-16 03:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('date', models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 6, 16, 8, 50, 24, 122131))),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(default='skyblue', max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 6, 16, 8, 50, 24, 122131))),
                ('status', models.BooleanField(default=False)),
                ('info', models.CharField(max_length=200)),
                ('belongsto_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.Lists')),
            ],
        ),
    ]
